/* PT Pulse 3D Designer — local/offline workshop v4 */
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let paths=[],selected=-1,tool='select',refImage=null,history=[],future=[],scale=1,pan={x:0,y:0},drag=null,dragNode=null,anchors=[],bridges=[],orbit={x:-.35,y:.65},orbitDrag=null;
const state={system:'gen2',stripW:8,stripH:6.5,clearance:.25,wall:1.5,ridge:.7,depth:6.5,diffuser:'none',wire:true,split:true,bedW:220,bedD:220,bedH:220,neon:true,channel:true,showParts:true};
function snap(){history.push(JSON.stringify({paths,anchors,bridges,state:{...state}}));if(history.length>40)history.shift();future=[]}
function restore(s){let d=JSON.parse(s);paths=d.paths||[];anchors=d.anchors||[];bridges=d.bridges||[];Object.assign(state,d.state||{});applyState();selected=Math.min(selected,paths.length-1);render()}
function undo(){if(!history.length)return;future.push(JSON.stringify({paths,anchors,bridges,state:{...state}}));restore(history.pop())}
function redo(){if(!future.length)return;history.push(JSON.stringify({paths,anchors,bridges,state:{...state}}));restore(future.pop())}
function dist(a,b){return Math.hypot(b.x-a.x,b.y-a.y)}
function length(p){let n=0;for(let i=1;i<p.length;i++)n+=dist(p[i-1],p[i]);return n}
function box(p){let xs=p.map(x=>x.x),ys=p.map(x=>x.y);return{x:Math.min(...xs),y:Math.min(...ys),w:Math.max(...xs)-Math.min(...xs),h:Math.max(...ys)-Math.min(...ys)}}
function allBox(){let a=paths.flatMap(p=>p.points);return a.length?box(a):{x:0,y:0,w:0,h:0}}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function pathD(p){return p.map((q,i)=>(i?'L':'M')+q.x.toFixed(2)+' '+q.y.toFixed(2)).join(' ')}
function download(name,data,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function svg(){let w=+$('#projectW').value||1000,h=+$('#projectH').value||700;return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}mm" height="${h}mm" viewBox="0 0 ${w} ${h}">${paths.map(p=>`<path d="${pathD(p.points)}" fill="none" stroke="${p.color}" stroke-width="${p.width}" stroke-linecap="round" stroke-linejoin="round"/>`).join('')}</svg>`}
function pieces(B){if(!state.split||!B.w||!B.h)return [{x:B.x,y:B.y,w:B.w,h:B.h}];let cols=Math.max(1,Math.ceil(B.w/state.bedW)),rows=Math.max(1,Math.ceil(B.h/state.bedD)),out=[];for(let y=0;y<rows;y++)for(let x=0;x<cols;x++)out.push({x:B.x+x*state.bedW,y:B.y+y*state.bedD,w:Math.min(state.bedW,B.w-x*state.bedW),h:Math.min(state.bedD,B.h-y*state.bedD)});return out}
function fit(){let B=allBox();if(!B.w&&!B.h){scale=.8;pan={x:100,y:80};updateTransform();return}let vw=$('#board').clientWidth-40,vh=$('#board').clientHeight-40;scale=Math.min(vw/(B.w+80),vh/(B.h+80));pan.x=vw/2-(B.x+B.w/2)*scale;pan.y=vh/2-(B.y+B.h/2)*scale;updateTransform()}
function updateTransform(){$('#svgwrap').style.transform=`translate(${pan.x}px,${pan.y}px) scale(${scale})`;$('#zoom').textContent=Math.round(scale*100)+'%'}
function addPoint(ev){let r=$('#design').getBoundingClientRect(),x=(ev.clientX-r.left-pan.x)/scale,y=(ev.clientY-r.top-pan.y)/scale;if(tool==='pen'){if(!drag){snap();paths.push({name:'Traço '+(paths.length+1),color:$('#color').value,width:+$('#width').value||8,points:[{x,y}]});selected=paths.length-1;drag=paths[selected]}else drag.points.push({x,y});render()}else if(tool==='anchor'){snap();anchors.push({x,y});render()}else if(tool==='bridge'){snap();bridges.push({x,y});render()}else if(tool==='select'){let hit=-1;for(let i=paths.length-1;i>=0;i--){let B=box(paths[i].points);if(x>=B.x-15&&x<=B.x+B.w+15&&y>=B.y-15&&y<=B.y+B.h+15){hit=i;break}}if(hit>=0){selected=hit;render()}}}
$('#board').addEventListener('pointerdown',e=>{if(e.target.closest('#nodes circle'))return;if(tool==='select'&&selected>=0){let p=screenToDesign(e);let pts=paths[selected].points;let best=-1,bd=Infinity;pts.forEach((q,i)=>{let d=Math.hypot(q.x-p.x,q.y-p.y);if(d<bd){bd=d;best=i}});if(bd<18){dragNode={i:best};snap();return}}addPoint(e)});
$('#board').addEventListener('pointermove',e=>{if(dragNode){let p=screenToDesign(e);paths[selected].points[dragNode.i]=p;render();return}if(drag&&tool==='pen'){let p=screenToDesign(e);drag.points.push(p);render()}});
$('#board').addEventListener('pointerup',()=>{drag=null;dragNode=null});
function screenToDesign(ev){let r=$('#design').getBoundingClientRect();return{x:(ev.clientX-r.left-pan.x)/scale,y:(ev.clientY-r.top-pan.y)/scale}}
$('#design').addEventListener('wheel',e=>{e.preventDefault();scale=Math.max(.08,Math.min(10,scale*(e.deltaY<0?1.1:.9)));updateTransform()},{passive:false});
function importSVG(text){let hidden=document.createElement('div');hidden.style.cssText='position:absolute;left:-99999px';hidden.innerHTML=text;document.body.appendChild(hidden);let svgEl=hidden.querySelector('svg'),found=[];if(!svgEl){hidden.remove();return}svgEl.querySelectorAll('path,line,polyline,polygon').forEach(el=>{try{let pts=[];if(el.tagName==='path'){let n=el.getTotalLength(),step=Math.max(1.5,n/1000);for(let d=0;d<=n;d+=step){let q=el.getPointAtLength(d);pts.push({x:q.x,y:q.y})}}else{let raw=el.getAttribute('points');if(raw)raw.trim().split(/\s+/).forEach(v=>{let a=v.split(',').map(Number);if(a.length>1)pts.push({x:a[0],y:a[1]})});else pts=[{x:+el.getAttribute('x1')||0,y:+el.getAttribute('y1')||0},{x:+el.getAttribute('x2')||0,y:+el.getAttribute('y2')||0}]}if(pts.length>1)found.push({name:el.getAttribute('id')||'SVG traço',color:el.getAttribute('stroke')||'#ffffff',width:state.stripW,points:pts})}catch{}});hidden.remove();if(found.length){snap();paths.push(...found);selected=paths.length-1;$('#status').textContent=`SVG importado: ${found.length} traços`;render();fit()}else alert('Não encontrei caminhos compatíveis no SVG.')}
$('#svgFile').onchange=e=>{let f=e.target.files[0];if(!f)return;let rd=new FileReader();rd.onload=()=>importSVG(rd.result);rd.readAsText(f)};
$('#imgFile').onchange=e=>{let f=e.target.files[0];if(!f)return;let u=URL.createObjectURL(f);refImage=new Image();refImage.onload=()=>{$('#reference').setAttribute('href',u);$('#reference').setAttribute('opacity',.45);$('#reference').setAttribute('width',$('#projectW').value);$('#reference').setAttribute('height',$('#projectH').value);$('#status').textContent='Referência carregada';};refImage.src=u};
function render(){let g=$('#design');g.innerHTML='';paths.forEach((p,i)=>{let e=document.createElementNS('http://www.w3.org/2000/svg','path');e.setAttribute('d',pathD(p.points));e.setAttribute('fill','none');e.setAttribute('stroke',p.color);e.setAttribute('stroke-width',p.width);e.setAttribute('stroke-linecap','round');e.setAttribute('stroke-linejoin','round');e.dataset.i=i;e.classList.toggle('selected',i===selected);e.addEventListener('pointerdown',ev=>{ev.stopPropagation();selected=i;render()});g.appendChild(e)});$('#nodes').innerHTML=selected>=0?paths[selected].points.map((p,i)=>`<circle cx="${p.x}" cy="${p.y}" r="4" data-i="${i}"/>`).join(''):'';let L=paths.reduce((a,p)=>a+length(p.points),0),B=allBox(),pcs=pieces(B),channelW=state.stripW+2*state.clearance+2*state.wall,channelH=state.depth+state.wall;$('#stat').textContent=`${Math.round(L)} mm · ${Math.round(B.w)} × ${Math.round(B.h)} mm · ${paths.length} traços · ${pcs.length} peça(s)`;$('#material').innerHTML=`<b>Materiais</b><br>NeonFlex: <b>${(L/1000).toFixed(2)} m</b><br>Canal: ${channelW.toFixed(2)} × ${channelH.toFixed(2)} mm<br>Filamento estimado: <b>${Math.max(.01,L*channelW*state.wall/1000000*1.24).toFixed(2)} kg</b><br>Peças: ${pcs.length}<br>Âncoras: ${anchors.length} · Bridges: ${bridges.length}<br>Cablagem: ${state.wire?'oculta':'normal'}<br>Difusor: ${state.diffuser}`;$('#layers').innerHTML=paths.map((p,i)=>`<div class="layer ${i===selected?'sel':''}" data-i="${i}">${i+1}. ${esc(p.name||'Traço')} <small>${length(p.points).toFixed(0)} mm</small></div>`).join('');$$('.layer').forEach(e=>e.onclick=()=>{selected=+e.dataset.i;render()});render3d()}
function applyState(){$('#system').value=state.system;$('#stripW').value=state.stripW;$('#stripH').value=state.stripH;$('#clearance').value=state.clearance;$('#wall').value=state.wall;$('#ridge').value=state.ridge;$('#depth').value=state.depth;$('#diffuser').value=state.diffuser;$('#wire').checked=state.wire;$('#split').checked=state.split;$('#bedW').value=state.bedW;$('#bedD').value=state.bedD}
function readState(){['stripW','stripH','clearance','wall','ridge','depth','bedW','bedD'].forEach(k=>state[k]=+$('#'+k).value);state.system=$('#system').value;state.diffuser=$('#diffuser').value;state.wire=$('#wire').checked;state.split=$('#split').checked;render()}
$('#system').onchange=()=>{if($('#system').value==='gen1'){$('#stripW').value=6.2;$('#stripH').value=10;$('#ridge').value=0;$('#depth').value=10}else{$('#stripW').value=8;$('#stripH').value=6.5;$('#ridge').value=.7;$('#depth').value=6.5}readState()};$$('input,select').forEach(e=>e.addEventListener('change',readState));
$$('[data-tool]').forEach(b=>b.onclick=()=>{$$('[data-tool]').forEach(x=>x.classList.remove('active'));b.classList.add('active');tool=b.dataset.tool;drag=null});
$('#new').onclick=()=>{if(confirm('Começar um projeto novo?')){snap();paths=[];selected=-1;anchors=[];bridges=[];render();fit()}};$('#undo').onclick=undo;$('#redo').onclick=redo;$('#fit').onclick=fit;$('#save').onclick=save;$('#svgExport').onclick=()=>download('ptpulse.svg',svg(),'image/svg+xml');$('#stl').onclick=exportSTL;$('#svgFileBtn').onclick=()=>$('#svgFile').click();$('#imgFileBtn').onclick=()=>$('#imgFile').click();$('#projectBtn').onclick=()=>$('#projectFile').click();$('#clear').onclick=()=>{if(paths.length){snap();paths=[];selected=-1;render()}};$('#delete').onclick=()=>{if(selected>=0){snap();paths.splice(selected,1);selected=-1;render()}};
function save(){let data=JSON.stringify({version:4,state,paths,anchors,bridges,projectW:$('#projectW').value,projectH:$('#projectH').value},null,2);download('ptpulse-projeto.json',data,'application/json')}
$('#projectFile').onchange=e=>{let f=e.target.files[0];if(!f)return;let rd=new FileReader();rd.onload=()=>{try{let d=JSON.parse(rd.result);paths=d.paths||[];Object.assign(state,d.state||{});anchors=d.anchors||[];bridges=d.bridges||[];$('#projectW').value=d.projectW||1000;$('#projectH').value=d.projectH||700;applyState();render();fit()}catch{alert('Projeto inválido')}};rd.readAsText(f)};
function exportSTL(){if(!paths.length){alert('Importa ou desenha pelo menos um traço.');return}let tris=[];const tw=state.stripW+2*state.clearance+2*state.wall, th=state.depth+state.wall;function T(a,b,c){tris.push([a,b,c])}function prism(a,b,w,h,z0=0){let dx=b.x-a.x,dy=b.y-a.y,l=Math.hypot(dx,dy)||1,nx=-dy/l*w/2,ny=dx/l*w/2,A=[{x:a.x+nx,y:a.y+ny,z:z0},{x:b.x+nx,y:b.y+ny,z:z0},{x:b.x-nx,y:b.y-ny,z:z0},{x:a.x-nx,y:a.y-ny,z:z0},{x:a.x+nx,y:a.y+ny,z:z0+h},{x:b.x+nx,y:b.y+ny,z:z0+h},{x:b.x-nx,y:b.y-ny,z:z0+h},{x:a.x-nx,y:a.y-ny,z:z0+h}];[[0,1,2],[0,2,3],[4,6,5],[4,7,6],[0,4,5],[0,5,1],[1,5,6],[1,6,2],[2,6,7],[2,7,3],[3,7,4],[3,4,0]].forEach(q=>T(A[q[0]],A[q[1]],A[q[2]]))}paths.forEach(p=>{for(let i=1;i<p.points.length;i++)prism(p.points[i-1],p.points[i],tw,th)});anchors.forEach(a=>cylinder(a.x,a.y,4,th+2));function cylinder(cx,cy,r,h){let N=12;for(let i=0;i<N;i++){let a=i*2*Math.PI/N,b=(i+1)*2*Math.PI/N,A={x:cx+Math.cos(a)*r,y:cy+Math.sin(a)*r,z:0},B={x:cx+Math.cos(b)*r,y:cy+Math.sin(b)*r,z:0},C={x:B.x,y:B.y,z:h},D={x:A.x,y:A.y,z:h},bot={x:cx,y:cy,z:0},top={x:cx,y:cy,z:h};T(bot,B,A);T(top,D,C);T(A,B,C);T(A,C,D)}}let out='solid ptpulse\n';tris.forEach(t=>{let u={x:t[1].x-t[0].x,y:t[1].y-t[0].y,z:t[1].z-t[0].z},v={x:t[2].x-t[0].x,y:t[2].y-t[0].y,z:t[2].z-t[0].z},n={x:u.y*v.z-u.z*v.y,y:u.z*v.x-u.x*v.z,z:u.x*v.y-u.y*v.x};out+=` facet normal ${n.x} ${n.y} ${n.z}\n  outer loop\n`;t.forEach(p=>out+=`   vertex ${p.x} ${p.y} ${p.z}\n`);out+='  endloop\n endfacet\n'});out+='endsolid ptpulse';download('ptpulse-neonflex.stl',out,'model/stl');$('#status').textContent='STL exportado — canal base segmentado'}
function project3D(p){let cy=Math.cos(orbit.y),sy=Math.sin(orbit.y),cx=Math.cos(orbit.x),sx=Math.sin(orbit.x);let x=p.x,y=p.y,z=p.z;let X=x*cy-z*sy,Z=x*sy+z*cy,Y=y*cx-Z*sx,D=y*sx+Z*cx;let s=380/(380+D);return{x:X*s,y:Y*s,z:D,s}}
function drawTube(ctx,pts,base){if(pts.length<2)return;let q=pts.map(p=>project3D({x:p.x,y:p.y,z:base}));ctx.beginPath();q.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.strokeStyle='#15171b';ctx.lineWidth=Math.max(5,state.stripW*1.8*q.reduce((a,v)=>a+v.s,0)/q.length);ctx.lineCap='round';ctx.stroke();ctx.beginPath();q.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.strokeStyle=state.neon?'#f2c94c':'#aeb4bd';ctx.lineWidth=Math.max(2,state.stripW*.72*q.reduce((a,v)=>a+v.s,0)/q.length);ctx.stroke()}
function render3d(){let c=$('#three'),dpr=devicePixelRatio||1,w=c.clientWidth||700,h=c.clientHeight||430;c.width=w*dpr;c.height=h*dpr;let x=c.getContext('2d');x.setTransform(dpr,0,0,dpr,0,0);x.clearRect(0,0,w,h);x.fillStyle='#080a0d';x.fillRect(0,0,w,h);let all=paths.flatMap(p=>p.points);if(!all.length){x.fillStyle='#8d939b';x.font='14px Arial';x.fillText('Importa um SVG ou desenha um traço para ver o 3D',24,36);return}let B=allBox(),cx=w/2,cy=h/2;let normalized=paths.map(p=>p.points.map(q=>({x:(q.x-(B.x+B.w/2))*.65,y:(q.y-(B.y+B.h/2))*.65,z:0})));x.save();x.translate(cx,cy);x.strokeStyle='#22262c';x.lineWidth=1;for(let i=-300;i<=300;i+=40){let a=project3D({x:i,y:160,z:-80}),b=project3D({x:i,y:160,z:180});x.beginPath();x.moveTo(a.x,a.y);x.lineTo(b.x,b.y);x.stroke()}for(let i=-200;i<=200;i+=40){let a=project3D({x:-300,y:i,z:0}),b=project3D({x:300,y:i,z:0});x.beginPath();x.moveTo(a.x,a.y);x.lineTo(b.x,b.y);x.stroke()}normalized.forEach(p=>drawTube(x,p,state.depth*.5));if(state.diffuser!=='none'){normalized.forEach(p=>{let q=p.map(v=>project3D({x:v.x,y:v.y,z:state.depth*.5+2}));x.beginPath();q.forEach((v,i)=>i?x.lineTo(v.x,v.y):x.moveTo(v.x,v.y));x.strokeStyle='#e8edf2';x.globalAlpha=.42;x.lineWidth=Math.max(3,state.stripW*.95);x.stroke();x.globalAlpha=1})}anchors.forEach(a=>{let q=project3D({x:(a.x-(B.x+B.w/2))*.65,y:(a.y-(B.y+B.h/2))*.65,z:state.depth*.5});x.fillStyle='#f2c94c';x.beginPath();x.arc(q.x,q.y,5,0,Math.PI*2);x.fill()});x.restore();x.fillStyle='#aeb4bd';x.font='12px Arial';x.fillText(`3D · ${state.system.toUpperCase()} · canal ${tw().toFixed(2)} mm · ${state.depth} mm`,18,22);x.fillText('Arrasta para rodar · roda para zoom',18,h-14)}
function tw(){return state.stripW+2*state.clearance+2*state.wall}
$('#three').addEventListener('pointerdown',e=>{orbitDrag={x:e.clientX,y:e.clientY,ox:orbit.x,oy:orbit.y};$('#three').setPointerCapture(e.pointerId)});$('#three').addEventListener('pointermove',e=>{if(!orbitDrag)return;orbit.y=orbitDrag.oy+(e.clientX-orbitDrag.x)*.01;orbit.x=orbitDrag.ox+(e.clientY-orbitDrag.y)*.01;render3d()});$('#three').addEventListener('pointerup',()=>orbitDrag=null);$('#three').addEventListener('wheel',e=>{e.preventDefault();render3d()},{passive:false});
applyState();render();setTimeout(fit,100);window.addEventListener('resize',()=>{fit();render3d()});