/* PT Pulse 3D Designer — local/offline workshop */
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let paths=[],selected=-1,tool='select',refImage=null,history=[],future=[],scale=1,pan={x:0,y:0},drag=null,anchors=[],bridges=[];
const state={system:'gen2',stripW:8,stripH:6.5,clearance:.25,wall:1.5,ridge:.7,depth:6.5,diffuser:'none',wire:true,split:true,bedW:220,bedD:220,bedH:220,neon:true};
function snap(){history.push(JSON.stringify(paths));if(history.length>40)history.shift();future=[]}
function restore(s){paths=JSON.parse(s);selected=Math.min(selected,paths.length-1);render()}
function undo(){if(!history.length)return;future.push(JSON.stringify(paths));restore(history.pop())}
function redo(){if(!future.length)return;history.push(JSON.stringify(paths));restore(future.pop())}
function dist(a,b){return Math.hypot(b.x-a.x,b.y-a.y)}
function length(p){let n=0;for(let i=1;i<p.length;i++)n+=dist(p[i-1],p[i]);return n}
function box(p){let xs=p.map(x=>x.x),ys=p.map(x=>x.y);return{x:Math.min(...xs),y:Math.min(...ys),w:Math.max(...xs)-Math.min(...xs),h:Math.max(...ys)-Math.min(...ys)}}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function pathD(p){return p.map((q,i)=>(i?'L':'M')+q.x.toFixed(2)+' '+q.y.toFixed(2)).join(' ')}
function svg(){let w=+$('#projectW').value||1000,h=+$('#projectH').value||700;return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}mm" height="${h}mm" viewBox="0 0 ${w} ${h}">${paths.map(p=>`<path d="${pathD(p.points)}" fill="none" stroke="${p.color}" stroke-width="${p.width}" stroke-linecap="round" stroke-linejoin="round"/>`).join('')}</svg>`}
function download(name,data,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function render(){let g=$('#design');g.innerHTML='';paths.forEach((p,i)=>{let e=document.createElementNS('http://www.w3.org/2000/svg','path');e.setAttribute('d',pathD(p.points));e.setAttribute('fill','none');e.setAttribute('stroke',p.color);e.setAttribute('stroke-width',p.width);e.setAttribute('stroke-linecap','round');e.setAttribute('stroke-linejoin','round');e.dataset.i=i;e.classList.toggle('selected',i===selected);e.addEventListener('pointerdown',ev=>{ev.stopPropagation();selected=i;render()});g.appendChild(e)});$('#nodes').innerHTML=selected>=0?paths[selected].points.map((p,i)=>`<circle cx="${p.x}" cy="${p.y}" r="4" data-i="${i}"/>`).join(''):'';let L=paths.reduce((a,p)=>a+length(p.points),0);let B=paths.length?paths.map(p=>box(p.points)).reduce((a,b)=>({x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),w:Math.max(a.x+a.w,b.x+b.w)-Math.min(a.x,b.x),h:Math.max(a.y+a.h,b.y+b.h)-Math.min(a.y,b.y)})):({x:0,y:0,w:0,h:0});$('#stat').textContent=`${Math.round(L)} mm · ${Math.round(B.w)} × ${Math.round(B.h)} mm · ${paths.length} traços`;$('#material').innerHTML=`<b>Materiais</b><br>NeonFlex: <b>${(L/1000).toFixed(2)} m</b><br>Canal/filamento: ~${Math.max(.01,L*(state.wall*2+state.stripW)/1000/100).toFixed(2)} kg<br>Peças: ${pieces(B).length}<br>Âncoras: ${anchors.length} · Bridges: ${bridges.length}`;$('#layers').innerHTML=paths.map((p,i)=>`<div class="layer ${i===selected?'sel':''}" data-i="${i}">${i+1}. ${esc(p.name||'Traço')} <small>${length(p.points).toFixed(0)} mm</small></div>`).join('');$$('.layer').forEach(e=>e.onclick=()=>{selected=+e.dataset.i;render()});render3d()}
function pieces(B){if(!state.split||!B.w||!B.h)return [{x:B.x,y:B.y,w:B.w,h:B.h}];let cols=Math.max(1,Math.ceil(B.w/state.bedW)),rows=Math.max(1,Math.ceil(B.h/state.bedD)),out=[];for(let y=0;y<rows;y++)for(let x=0;x<cols;x++)out.push({x:B.x+x*state.bedW,y:B.y+y*state.bedD,w:Math.min(state.bedW,B.w-x*state.bedW),h:Math.min(state.bedD,B.h-y*state.bedD)});return out}
function fit(){if(!paths.length)return;let all=paths.flatMap(p=>p.points),B=box(all),vw=$('#board').clientWidth-40,vh=$('#board').clientHeight-40;scale=Math.min(vw/(B.w+80),vh/(B.h+80));pan.x=vw/2-(B.x+B.w/2)*scale;pan.y=vh/2-(B.y+B.h/2)*scale;updateTransform()}
function updateTransform(){$('#svgwrap').style.transform=`translate(${pan.x}px,${pan.y}px) scale(${scale})`;$('#zoom').textContent=Math.round(scale*100)+'%'}
function addPoint(ev){let r=$('#design').getBoundingClientRect(),x=(ev.clientX-r.left-pan.x)/scale,y=(ev.clientY-r.top-pan.y)/scale;if(tool==='pen'){if(drag){drag.points.push({x,y});render()}else{snap();paths.push({name:'Traço',color:$('#color').value,width:+$('#width').value||8,points:[{x,y}]});selected=paths.length-1;drag=paths[selected];render()}}else if(tool==='select'){let hit=-1;paths.forEach((p,i)=>{let B=box(p.points);if(x>=B.x-15&&x<=B.x+B.w+15&&y>=B.y-15&&y<=B.y+B.h+15)hit=i});if(hit>=0){selected=hit;render()}}}
$('#board').addEventListener('pointerdown',e=>{if(e.target.closest('#nodes circle'))return;addPoint(e)});$('#board').addEventListener('pointerup',()=>{if(tool==='pen')drag=null});$('#board').addEventListener('dblclick',()=>{if(tool==='pen')drag=null});
$('#design').addEventListener('wheel',e=>{e.preventDefault();scale=Math.max(.1,Math.min(8,scale*(e.deltaY<0?1.1:.9)));updateTransform()},{passive:false});
function importSVG(text){let doc=new DOMParser().parseFromString(text,'image/svg+xml'),root=doc.documentElement,view=(root.getAttribute('viewBox')||'0 0 1000 700').split(/\s+/).map(Number);let hidden=document.createElement('div');hidden.style.cssText='position:absolute;left:-99999px';hidden.innerHTML=text;document.body.appendChild(hidden);let svgEl=hidden.querySelector('svg');let found=[];svgEl.querySelectorAll('path,line,polyline,polygon').forEach(el=>{try{let pts=[];if(el.tagName==='path'){let n=el.getTotalLength(),step=Math.max(2,n/600);for(let d=0;d<=n;d+=step){let q=el.getPointAtLength(d);pts.push({x:q.x,y:q.y})}}else{let raw=el.getAttribute('points');if(raw)raw.trim().split(/\s+/).forEach(v=>{let a=v.split(',').map(Number);if(a.length>1)pts.push({x:a[0],y:a[1]})});else{let x1=+el.getAttribute('x1')||0,y1=+el.getAttribute('y1')||0,x2=+el.getAttribute('x2')||0,y2=+el.getAttribute('y2')||0;pts=[{x:x1,y:y1},{x:x2,y:y2}]}}if(pts.length>1)found.push({name:el.getAttribute('id')||'SVG traço',color:'#fff',width:state.stripW,points:pts})}catch{}});hidden.remove();if(found.length){snap();paths.push(...found);selected=paths.length-1;$('#status').textContent=`SVG importado: ${found.length} traços`;render();fit()}}
$('#svgFile').onchange=e=>{let f=e.target.files[0];if(!f)return;let rd=new FileReader();rd.onload=()=>importSVG(rd.result);rd.readAsText(f)};
$('#imgFile').onchange=e=>{let f=e.target.files[0];if(!f)return;let u=URL.createObjectURL(f);refImage=new Image();refImage.onload=()=>{let im=$('#reference');im.href=u;im.setAttribute('opacity',.45);im.setAttribute('x',0);im.setAttribute('y',0);im.setAttribute('width',$('#projectW').value);im.setAttribute('height',$('#projectH').value);$('#status').textContent='Referência carregada';};refImage.src=u};
function exportSTL(){if(!paths.length){alert('Importa ou desenha pelo menos um traço.');return}let tris=[];function tri(a,b,c){tris.push([a,b,c])}function prism(a,b,w,h){let dx=b.x-a.x,dy=b.y-a.y,l=Math.hypot(dx,dy)||1,nx=-dy/l*w/2,ny=dx/l*w/2;let z0=0,z1=h,A=[{x:a.x+nx,y:a.y+ny,z:z0},{x:b.x+nx,y:b.y+ny,z:z0},{x:b.x-nx,y:b.y-ny,z:z0},{x:a.x-nx,y:a.y-ny,z:z0},{x:a.x+nx,y:a.y+ny,z:z1},{x:b.x+nx,y:b.y+ny,z:z1},{x:b.x-nx,y:b.y-ny,z:z1},{x:a.x-nx,y:a.y-ny,z:z1}];[[0,1,2],[0,2,3],[4,6,5],[4,7,6],[0,4,5],[0,5,1],[1,5,6],[1,6,2],[2,6,7],[2,7,3],[3,7,4],[3,4,0]].forEach(t=>tri(A[t[0]],A[t[1]],A[t[2]]))}paths.forEach(p=>{for(let i=1;i<p.points.length;i++)prism(p.points[i-1],p.points[i],state.stripW+state.clearance*2+state.wall*2,state.depth)});let out='solid ptpulse\n';tris.forEach(t=>{let u={x:t[1].x-t[0].x,y:t[1].y-t[0].y,z:t[1].z-t[0].z},v={x:t[2].x-t[0].x,y:t[2].y-t[0].y,z:t[2].z-t[0].z},n={x:u.y*v.z-u.z*v.y,y:u.z*v.x-u.x*v.z,z:u.x*v.y-u.y*v.x};out+=` facet normal ${n.x} ${n.y} ${n.z}\n  outer loop\n`;t.forEach(p=>out+=`   vertex ${p.x} ${p.y} ${p.z}\n`);out+='  endloop\n endfacet\n'});out+='endsolid ptpulse';download('ptpulse-neonflex.stl',out,'model/stl');$('#status').textContent='STL exportado (geometria aproximada)'}
function save(){let data=JSON.stringify({version:3,state,paths,anchors,bridges,projectW:$('#projectW').value,projectH:$('#projectH').value},null,2);download('ptpulse-projeto.json',data,'application/json')}
$('#projectFile').onchange=e=>{let f=e.target.files[0];if(!f)return;let rd=new FileReader();rd.onload=()=>{try{let d=JSON.parse(rd.result);paths=d.paths||[];Object.assign(state,d.state||{});anchors=d.anchors||[];bridges=d.bridges||[];$('#projectW').value=d.projectW||1000;$('#projectH').value=d.projectH||700;applyState();render();fit()}catch{alert('Projeto inválido')}};rd.readAsText(f)};
function applyState(){$('#system').value=state.system;$('#stripW').value=state.stripW;$('#stripH').value=state.stripH;$('#clearance').value=state.clearance;$('#wall').value=state.wall;$('#ridge').value=state.ridge;$('#depth').value=state.depth;$('#diffuser').value=state.diffuser;$('#wire').checked=state.wire;$('#split').checked=state.split;$('#bedW').value=state.bedW;$('#bedD').value=state.bedD}
function readState(){['stripW','stripH','clearance','wall','ridge','depth','bedW','bedD'].forEach(k=>state[k]=+$('#'+k).value);state.system=$('#system').value;state.diffuser=$('#diffuser').value;state.wire=$('#wire').checked;state.split=$('#split').checked;render()}
$('#system').onchange=()=>{if($('#system').value==='gen1'){$('#stripW').value=6.2;$('#stripH').value=10;$('#ridge').value=0}else{$('#stripW').value=8;$('#stripH').value=6.5;$('#ridge').value=.7}readState()};$$('input,select').forEach(e=>e.addEventListener('change',readState));
$$('[data-tool]').forEach(b=>b.onclick=()=>{$$('[data-tool]').forEach(x=>x.classList.remove('active'));b.classList.add('active');tool=b.dataset.tool});
$('#new').onclick=()=>{if(confirm('Começar um projeto novo?')){snap();paths=[];selected=-1;anchors=[];bridges=[];render();fit()}};$('#undo').onclick=undo;$('#redo').onclick=redo;$('#fit').onclick=fit;$('#save').onclick=save;$('#svgExport').onclick=()=>download('ptpulse.svg',svg(),'image/svg+xml');$('#stl').onclick=exportSTL;$('#svgFileBtn').onclick=()=>$('#svgFile').click();$('#imgFileBtn').onclick=()=>$('#imgFile').click();$('#projectBtn').onclick=()=>$('#projectFile').click();$('#clear').onclick=()=>{if(paths.length){snap();paths=[];selected=-1;render()}};$('#delete').onclick=()=>{if(selected>=0){snap();paths.splice(selected,1);selected=-1;render()}};
function render3d(){let c=$('#three'),x=c.getContext('2d'),w=c.width=c.clientWidth*devicePixelRatio||600,h=c.height=c.clientHeight*devicePixelRatio||400;x.clearRect(0,0,w,h);x.fillStyle='#080a0d';x.fillRect(0,0,w,h);let all=paths.flatMap(p=>p.points);if(!all.length){x.fillStyle='#888';x.fillText('Importa um SVG ou desenha um traço',30,40);return}let B=box(all),s=Math.min((w-80)/(B.w||1),(h-100)/(B.h||1)),cx=w/2-(B.x+B.w/2)*s,cy=h/2-(B.y+B.h/2)*s;x.save();x.translate(cx,cy);x.scale(s,s);paths.forEach(p=>{x.beginPath();p.points.forEach((q,i)=>i?x.lineTo(q.x,q.y):x.moveTo(q.x,q.y));x.strokeStyle=state.neon?p.color:'#bbb';x.lineWidth=state.stripW/s; x.lineCap='round';x.stroke();x.strokeStyle='#333';x.lineWidth=(state.stripW+state.wall*2)/s;x.globalCompositeOperation='destination-over';x.stroke();x.globalCompositeOperation='source-over'});x.restore();x.fillStyle='#aaa';x.fillText(`3D · ${state.system.toUpperCase()} · ${state.depth} mm`,20,25)}
$('#three').addEventListener('click',()=>{});window.addEventListener('resize',fit);applyState();render();setTimeout(fit,100);
