/* PT Pulse workshop upgrade — additive, no external libraries */
(()=>{
const $=s=>document.querySelector(s);
function addTools(){const h=[...document.querySelectorAll('h3')].find(x=>x.textContent.trim()==='Oficina');if(!h)return;const g=h.parentElement;if(g.querySelector('[data-tool="anchor"]'))return;const row=document.createElement('div');row.className='grid2';row.innerHTML='<button class="tool" data-tool="anchor">⚓ Âncora</button><button class="tool" data-tool="bridge">▰ Bridge</button>';g.appendChild(row);row.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tool]').forEach(x=>x.classList.remove('active'));b.classList.add('active');window.tool=b.dataset.tool;$('#status').textContent=b.dataset.tool==='anchor'?'Clique no desenho para colocar uma âncora':'Clique no desenho para colocar uma bridge'});}
function add3DPanel(){const card=document.querySelector('.modalcard');if(!card||document.getElementById('advanced3d'))return;const p=document.createElement('div');p.id='advanced3d';p.style.cssText='display:flex;gap:6px;flex-wrap:wrap;margin-top:8px';p.innerHTML='<button id="xminus">↶</button><button id="xplus">↷</button><button id="yminus">↑</button><button id="yplus">↓</button><button id="zin">＋ Zoom</button><button id="zout">－ Zoom</button><button id="reset3">Reset 3D</button><button id="diff3">STL difusor</button>';card.appendChild(p);$('#xminus').onclick=()=>{orbit.y-=.15;render3d()};$('#xplus').onclick=()=>{orbit.y+=.15;render3d()};$('#yminus').onclick=()=>{orbit.x-=.12;render3d()};$('#yplus').onclick=()=>{orbit.x+=.12;render3d()};$('#zin').onclick=()=>{orbit.zoom=Math.min(3,(orbit.zoom||1)*1.15);render3d()};$('#zout').onclick=()=>{orbit.zoom=Math.max(.35,(orbit.zoom||1)/1.15);render3d()};$('#reset3').onclick=()=>{orbit={x:-.35,y:.65,zoom:1};render3d()};$('#diff3').onclick=()=>window.exportDiffuser?exportDiffuser():alert('Seleciona um difusor primeiro.');}
function enhance3D(){if(typeof render3d!=='function')return;const old=render3d;window.render3d=function(){add3DPanel();old();};const c=$('#three');if(!c||c.dataset.orbit)return;c.dataset.orbit='1';c.addEventListener('pointerdown',e=>{orbit.drag=true;orbit.px=e.clientX;orbit.py=e.clientY;c.setPointerCapture?.(e.pointerId)});c.addEventListener('pointerup',()=>orbit.drag=false);c.addEventListener('pointercancel',()=>orbit.drag=false);c.addEventListener('pointermove',e=>{if(!orbit.drag)return;orbit.y+=(e.clientX-orbit.px)*.012;orbit.x+=(e.clientY-orbit.py)*.012;orbit.px=e.clientX;orbit.py=e.clientY;old()});}
function addExportMenu(){const stl=$('#stl');if(!stl||document.getElementById('exportExtras'))return;const wrap=document.createElement('span');wrap.id='exportExtras';wrap.style.cssText='display:flex;gap:6px';wrap.innerHTML='<button id="diffExportTop">Difusor STL</button>';stl.parentElement.insertBefore(wrap,stl.nextSibling);$('#diffExportTop').onclick=()=>window.exportDiffuser?exportDiffuser():alert('Seleciona um difusor no painel.');}
function showProduction(){const right=[...document.querySelectorAll('h3')].find(x=>x.textContent.trim()==='Notas');if(!right)return;const g=right.parentElement;if(g.dataset.prod)return;g.dataset.prod='1';const b=document.createElement('div');b.className='group';b.innerHTML='<h3>Verificação de fabrico</h3><div class="muted" id="prodCheck">A analisar…</div>';g.parentElement.insertBefore(b,g);const check=()=>{if(typeof materialStats!=='function')return;const s=materialStats(),issues=[];if(s.L<50)issues.push('Traço muito curto');if(channelWidth&&channelWidth()<state.stripW+2*state.wall)issues.push('Canal sem folga suficiente');if(state.split&&pieces(s.B).length>1)issues.push(`${pieces(s.B).length} peças pela mesa configurada`);if(state.wire===false)issues.push('Cablagem escondida desativada');$('#prodCheck').innerHTML=issues.length?issues.map(x=>'• '+x).join('<br>'):'✓ Geometria dentro dos parâmetros atuais';};setTimeout(check,300);}
function boot(){addTools();add3DPanel();enhance3D();addExportMenu();showProduction();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,50));else setTimeout(boot,50);
})();